In [2]:
import pandas as pd
data = pd.read_excel('/content/Chisquare.xlsx') #Importing data into environment
data

Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70
5             Total               240          360    600

# State the Hypotheses:
* **Null Hypothesis:** There is no significant association between the type of device purchased and customer satisfaction.
* **Alternate Hypothesis:** There is a significant association between the type of device purchased and customer satisfaction.

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
import numpy as np
df = np.random.randint(0,1,10).reshape((5,2)) #Creating a dummy matrix for store Expected frequencies
df

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

# Compute the Chi-Square Statistic:

In [5]:
for i in range(5):
    for j in range(2):
        df[i][j] = (data.loc[i][3]*data.loc[5][j+1])/data.loc[5][3] #Updating the Expected frequencies to dummy matrix
df

array([[ 48,  72],
       [ 72, 108],
       [ 60,  90],
       [ 32,  48],
       [ 28,  42]])

In [6]:
df1 = np.random.randint(0,1,10).reshape((5,2))
for i in range(5):
    for j in range(2):
        df1[i][j] = data.loc[i][j+1] #Separate main data points from data source for easy calcurations
df1

array([[ 50,  70],
       [ 80, 100],
       [ 60,  90],
       [ 30,  50],
       [ 20,  50]])

In [7]:
X = []
for i in range(5):
    for j in range(2):
        X.append((((df1[i][j]-df[i][j])**2)/df[i][j])) #Calculating the Chi-Square statistics for each data point and append to x
X_Square=round(sum(X),3) #Calculating the sum of Chi-Square statistics for all data point for X^2
X_Square

5.638

# Determine the Critical Value:

In [8]:
degree_of_freedom = (len(df1)-1)*(len(df1.T)-1) #Calculating the degree of freedom
degree_of_freedom

4

In [9]:
from scipy.stats import chi2

df = 4  # degrees of freedom
alpha = 0.05  # significance level

Critical_Value = round(chi2.ppf(1 - alpha, df),3) # Calculating critical value
Critical_Value

9.488

# Make a Decision:

In [10]:
if X_Square > Critical_Value: #Compare the Chi-Square statistic with the critical value to decide whether to reject the null hypothesis
    print("Reject The Null Hypothesis")
else:
    print("Failed To Reject The Null Hypothesis")

Failed To Reject The Null Hypothesis


# Conclusion

Based on the Chi-square value, we accept the alternate hypothesis, indicating a significant association between the type of device purchased and the customer's satisfaction level.